import React,{useState}from'react';import{createRoot}from'react-dom/client';import{createPortal}from'react-dom';import{ArrowLeft,ArrowRight,Check,ChevronDown,Menu,Target,Volume2,VolumeX,X,Scale,ShieldAlert,GraduationCap,Users,Globe2,Search,BarChart3,Wrench,RefreshCw}from'lucide-react';import'./styles.css';const A='/assets/';
const tabs=['The weak point','What it means','Threat sources','Four-step approach','Tools','Exam lens'];
const threats=[
['Regulatory Changes','05-regulatory.png','New laws or regulatory updates that directly affect project scope, process, or deliverables. Example: a new data privacy regulation taking effect midway through a project that wasn\'t designed around it.'],
['Technical Failures','06-technical.png','Defects in software, systems, or infrastructure that lead directly to non-compliance. Example: a hospital application storing patient data without encryption — a technical gap that\'s simultaneously a compliance failure.'],
['Lack of Awareness','07-awareness.png','Violations that happen unintentionally because team members simply don\'t know a requirement exists. Example: contractors never trained on mandatory safety protocols, not out of negligence, but because nobody ensured they knew the requirement in the first place.'],
['Resource Constraints','08-resources.png','Limited budgets, tools, or skilled personnel making it genuinely difficult to sustain compliance over time. Example: scheduled compliance testing that gets skipped because of a funding gap or staffing shortage — the requirement didn\'t disappear, the capacity to meet it did.'],
['Market Expansion','09-market.png','Entering new regions or industries introduces compliance requirements the team may not even know exist yet. Example: launching a product in the EU without first confirming it meets GDPR standards — a requirement invisible to a team that\'s never operated in that market before.']];
const steps=[
['Identify Compliance Risks','10-identify.png','Gather insight through risk workshops, expert interviews, risk checklists, and a risk breakdown structure — the same RBS discipline covered earlier, applied specifically to compliance. Example: a healthcare technology project\'s compliance risks might include shifting HIPAA guidelines, potential medical device software malfunction, and the risk of a patient confidentiality breach — each a distinct, nameable threat.'],
['Analyze Risks','11-analyze.png','Apply qualitative or quantitative techniques to assess likelihood and impact — the same probability-impact discipline covered earlier, using a probability-impact matrix or risk scoring model to prioritize. Example: in a banking platform rollout, a data encryption flaw might carry both high likelihood and critical impact, making it an immediate top-priority compliance risk.'],
['Develop Risk Responses','12-respond.png','For each high-priority threat, choose an actual response strategy — avoid (change the plan to eliminate the risk entirely), mitigate (reduce its likelihood or impact), transfer (shift it to a vendor or insurer), or accept (acknowledge it and monitor). Example: responding to a risk of violating new privacy laws by investing in stronger encryption and commissioning a legal review of every data flow is a clear mitigation response.'],
['Monitor and Control','13-monitor.png','Set up continuous monitoring — risk reviews built into every sprint or project phase, a live risk dashboard, and periodic audits. Example: a financial project running monthly compliance checkpoints specifically to confirm its Anti-Money Laundering protocols remain in place and genuinely effective.']];
const reveals={hook:{title:'Determine Potential Threats to Compliance',image:'02-hook-modal.png',text:'Compliance works the same way. This lesson is about identifying, assessing, and responding to potential threats to compliance before they become an actual breach — keeping a project genuinely in the clear, not just hoping it stays that way.'},meaning:{title:'What This Enabler Means',image:'04-enabler-modal.png',text:'This enabler asks the project manager to proactively identify the risks that could cause a project to breach legal, regulatory, or internal standards. These threats aren\'t always obvious — they can emerge from technical flaws, shifting regulation, or simple misunderstanding — but the consequences carry real weight. Non-compliance isn\'t just an unchecked box. It\'s a risk multiplier, capable of triggering penalties, lawsuits, reputational damage, or even a full project shutdown.'},tools:{title:'Tools to Support Compliance Risk Management',image:'15-tools-modal.png',text:'A risk register logs, monitors, and assigns owners to compliance risks specifically. A risk breakdown structure organizes compliance threats into legal, financial, and security tiers. A risk matrix visualizes severity to help prioritize response. And compliance audit logs document the checks actually performed and any corrective action taken as a result.'},exam:{title:'Synthesis (Exam Lens)',image:'17-exam-modal.png',text:'Compliance threats can emerge from regulatory change, technical failure, lack of awareness, resource constraints, or market expansion into unfamiliar territory. A structured, four-step approach — identifying risks, analyzing their likelihood and impact, developing a genuine response strategy, and monitoring continuously — turns compliance from a reactive scramble into a proactive discipline, using the same risk register, RBS, and matrix tools already built elsewhere in project risk management. Compliance isn\'t just a requirement to check off. It\'s an ongoing responsibility. Determining potential threats early is what shifts a project from reactive to proactive — from managing risk after it\'s already become a problem, to genuine readiness before it ever gets the chance to.',bullets:['Five threat sources: regulatory changes, technical failures, lack of awareness, resource constraints, market expansion','Four-step approach: identify (workshops, RBS), analyze (probability-impact), develop responses (avoid/mitigate/transfer/accept), monitor and control (continuous)','Strengthening a control (like encryption) plus review is mitigation — reducing likelihood/impact, not eliminating, transferring, or merely watching','Reuses existing tools: risk register, risk RBS, risk matrix, compliance audit logs — no new toolkit required']}};
const quiz={q:'Scenario: Your project team identifies a high risk of violating new privacy laws due to unclear data-handling procedures. The team decides to strengthen encryption and involve legal experts to review all data flows. Which compliance risk response strategy is being applied?',a:['Accept','Transfer','Avoid','Mitigate'],good:'Correct! Strengthening encryption and adding legal review are both actions that reduce the likelihood and potential impact of a compliance breach — this is mitigation in direct action.',bad:'Reconsider — accept means monitoring without active intervention, transfer means shifting responsibility to a third party, and avoid means eliminating the risky activity entirely. This team is actively reducing the risk themselves, not doing any of those three.'};
function Modal({d,close,read}){const[step,setStep]=useState(0);return createPortal(<div className="modal-backdrop" onClick={close}><section className="focus-modal" onClick={e=>e.stopPropagation()}><button className="modal-x" onClick={close}><X/></button>{!step?<><img className="modal-illustration" src={A+d.image}/><h3>{d.title}</h3><div className="modal-copy"><p>{d.text}</p></div></>:<div className="memory-step"><p className="eyebrow">EXAM-RELEVANT ENABLERS TO REMEMBER</p><ul>{d.bullets.map(x=><li key={x}>{x}</li>)}</ul></div>}{d.bullets&&!step?<button className="modal-action" onClick={()=>setStep(1)}>Next <ArrowRight/></button>:<button className="modal-action" onClick={()=>{read();close()}}>Mark as read <Check/></button>}</section></div>,document.body)}
function Quiz({finish}){const[p,setP]=useState(null);return createPortal(<div className="knowledge-backdrop"><section className="knowledge-modal"><p className="quiz-label"><Target/> MICRO KNOWLEDGE CHECK</p><h3>{quiz.q}</h3><div className="answers vertical">{quiz.a.map((x,i)=><button key={x} onClick={()=>setP(i)} className={p===i?(i===3?'correct':'wrong'):''}><span>{'ABCD'[i]}</span>{x}</button>)}</div>{p!==null&&<><p className={`feedback ${p===3?'good':'bad'}`}>{p===3?quiz.good:quiz.bad}</p><button className="finish-check" onClick={finish}>Finish check <ArrowRight/></button></>}</section></div>,document.body)}
const icons=[Scale,ShieldAlert,GraduationCap,Users,Globe2,Search,BarChart3,Wrench,RefreshCw];
function Cards({items,seen,setModal,offset=0}){return <div className={`direct-card-grid count-${items.length}`}>{items.map((x,i)=>{const I=icons[i+offset];return <button className={`direct-detail-card ${seen.includes(i)?'visited':''}`} onClick={()=>setModal({title:x[0],image:x[1],text:x[2],index:i})} key={x[0]}><span className="direct-card-icon"><I/></span><span className="direct-card-copy"><small>{seen.includes(i)?<><Check/> READ</>:String(i+1).padStart(2,'0')}</small><strong>{x[0]}</strong></span><ArrowRight className="direct-card-arrow"/></button>})}</div>}
function App(){const[s,setS]=useState(0),[done,setDone]=useState(Array(6).fill(false)),[modal,setModal]=useState(),[seenThreats,setSeenThreats]=useState([]),[seenSteps,setSeenSteps]=useState([]),[quizOpen,setQuizOpen]=useState(false),[sound,setSound]=useState(true);const mark=i=>setDone(v=>v.map((x,n)=>n===i?true:x)),go=i=>{if(i>=0&&i<6&&(i===0||done[i-1]))setS(i)};const read=()=>{if(modal?.index!==undefined){const setter=s===2?setSeenThreats:setSeenSteps;const seen=s===2?seenThreats:seenSteps;const n=[...new Set([...seen,modal.index])];setter(n);if((s===2&&n.length===5))mark(2);if(s===3&&n.length===4)setQuizOpen(true)}else mark(s)};return <div className="app"><header><button className="course"><Menu/> Project Management Professional <ChevronDown/></button><div className="dots">{Array.from({length:10},(_,i)=><span key={i} className={i<9?'past':i===9?'current':''}>{i<9&&<Check/>}</span>)}</div><div className="tools"><button onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}{sound?'Sound on':'Sound off'}</button><button>Quit</button></div></header><div className="lesson-frame"><div className="section-label">SECTION {s+1} OF 6</div><nav style={{gridTemplateColumns:'repeat(6,1fr)'}}>{tabs.map((t,i)=><button key={t} onClick={()=>go(i)} disabled={i&&!done[i-1]} className={i===s?'active':done[i]?'complete':''}>{done[i]&&<Check/>}{t}</button>)}</nav><main>
{s===0&&<section className="hero"><div><p className="eyebrow">LESSON 4.11.3</p><h1>Determine Potential Threats to Compliance</h1><p>A ship's crew doesn't wait for a hull breach to start checking for leaks. They inspect known weak points, watch weather patterns, and know exactly which conditions tend to precede trouble — because by the time water is visibly rising on deck, the response options have already narrowed dramatically.</p><button className="primary" onClick={()=>setModal(reveals.hook)}>Reveal the weak point <ArrowRight/></button></div><img src={A+'01-hook.png'}/></section>}
{s===1&&<section className="hero"><div><h2>What This Enabler Means</h2><p>These threats rarely announce themselves. That's exactly why watching for them proactively is the whole point of this enabler.</p><button className="primary" onClick={()=>setModal(reveals.meaning)}>Reveal what it means <ArrowRight/></button></div><img src={A+'03-enabler.png'}/></section>}
{s===2&&<section className="components"><h2>Five Sources of Compliance Threats</h2><p>Five sources account for most compliance threats worth actively watching for. Click each to explore.</p><Cards items={threats} seen={seenThreats} setModal={setModal}/></section>}
{s===3&&<section className="components"><h2>Four Steps to Determining Compliance Threats</h2><p>A structured, four-step approach turns this from a vague worry into a manageable discipline. Click each step to explore.</p><Cards items={steps} seen={seenSteps} setModal={setModal} offset={5}/></section>}
{s===4&&<section className="hero"><div><h2>Tools to Support Compliance Risk Management</h2><p>None of this requires inventing a new toolkit from scratch — the same tools already covered elsewhere in this course apply directly here.</p><button className="primary" onClick={()=>setModal(reveals.tools)}>Reveal the toolkit <ArrowRight/></button></div><img src={A+'14-tools.png'}/></section>}
{s===5&&<section className="hero"><div><p className="eyebrow">EXAM LENS</p><h2>Back to that ship's crew one more time —</h2><p>because by the time water is visibly rising on deck, the response options have already narrowed.</p><button className="primary" onClick={()=>setModal(reveals.exam)}>Reveal the exam lens <ArrowRight/></button></div><img src={A+'16-exam.png'}/></section>}
</main><footer><button onClick={()=>go(s-1)} disabled={!s}><ArrowLeft/> Previous</button><button className="continue" onClick={()=>go(s+1)} disabled={!done[s]}>{s===5?'Complete':'Continue'} <ArrowRight/></button></footer></div>{modal&&<Modal d={modal} close={()=>setModal()} read={read}/>} {quizOpen&&<Quiz finish={()=>{setQuizOpen(false);mark(3)}}/>}</div>}createRoot(document.getElementById('root')).render(<App/>);
